Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |docker, override|
    override.vm.box = nil
    docker.build_dir = "."
    override.ssh.insert_key = true
    docker.has_ssh = true
    docker.privileged = true
  end
   config.vm.provision "file", source: "k8s-examples", destination: "/home/vagrant/k8s-examples"
end
