Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |docker, override|
    override.vm.box = nil
    docker.build_dir = "."
    override.ssh.insert_key = true
    docker.has_ssh = true
    docker.privileged = true
  end
  config.vm.provision "file", source: "~/Development/docker/example-dockerfile", destination: "/home/vagrant/example-dockerfile"
  config.vm.provision "file", source: "~/Development/docker/example-dockercompose", destination: "/home/vagrant/example-dockercompose"
end
