ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	boxes = [
		{
			:name => "host1",
			:ip => "192.168.29.50"
		},
		{
			:name => "host2",
			:ip => "192.168.29.51"
		},
		{
			:name => "host3",
			:ip => "192.168.29.52"
		}
	]

	boxes.each do |opts|
		config.vm.define opts[:name] do |config|
			config.vm.hostname = opts[:name]
			# config.vm.network :private_network, ip: opts[:ip]
			# config.ssh.host = opts[:ip]
			config.vm.provider "docker" do |docker, override|
				override.vm.box = nil
				docker.build_dir = "."
				# docker.image = "rofrano/vagrant-provider:ubuntu"
				# override.ssh.insert_key = true
				docker.has_ssh = true
				docker.privileged = true
				docker.create_args = ['--cpuset-cpus=2']
				docker.create_args = ['--memory=2g']
			end
		end
	end
end
